package com.logpie.shopping.tool.model;

import com.logpie.framework.db.annotation.DatabaseKey;
import com.logpie.framework.db.annotation.DatabaseKey.ColumnType;
import com.logpie.framework.db.annotation.DatabaseTable;
import com.logpie.shopping.tool.repository.BrandRepository;

@DatabaseTable(name = BrandRepository.DB_TABLE_NAME_BRAND)
public class Brand extends LogpieModel {

	private String mBrandId;
	private String mBrandName;

	/**
	 * Constructor for creating a brand
	 * 
	 * @param brandName
	 */
	public Brand(final String brandName) {
		this.mBrandName = brandName;
	}

	/**
	 * 
	 * @param brandId
	 * @param brandName
	 */
	public Brand(final String brandId, final String brandName) {
		this.mBrandId = brandId;
		this.mBrandName = brandName;
	}

	@DatabaseKey(name = BrandRepository.DB_KEY_BRAND_ID, type = ColumnType.LONG, autoGenerated = true, isPrimaryKey = true)
	public String getBrandId() {
		return mBrandId;
	}

	@DatabaseKey(name = BrandRepository.DB_KEY_BRAND_NAME, type = ColumnType.STRING)
	public String getBrandName() {
		return mBrandName;
	}

	public void setBrandName(final String brandName) {
		this.mBrandName = brandName;
	}
}
