package com.logpie.shopping.tool.model;

import com.logpie.framework.db.annotation.DatabaseKey;
import com.logpie.framework.db.annotation.DatabaseKey.ColumnType;
import com.logpie.framework.db.annotation.DatabaseTable;
import com.logpie.shopping.tool.repository.CategoryRepository;

@DatabaseTable(name = CategoryRepository.DB_TABLE_NAME_CATEGORY)
public class Category extends LogpieModel {
	private String mCategoryId;
	private String mCategoryName;

	/**
	 * Constructor for creating a category
	 * 
	 * @param categoryName
	 */
	public Category(final String categoryName) {
		this.mCategoryName = categoryName;
	}

	/**
	 * 
	 * @param categoryId
	 * @param categoryName
	 */
	public Category(final String categoryId, final String categoryName) {
		this.mCategoryId = categoryId;
		this.mCategoryName = categoryName;
	}

	@DatabaseKey(name = CategoryRepository.DB_KEY_CATEGORY_ID, type = ColumnType.LONG, autoGenerated = true, isPrimaryKey = true)
	public String getCategoryId() {
		return mCategoryId;
	}

	@DatabaseKey(name = CategoryRepository.DB_KEY_CATEGORY_NAME, type = ColumnType.STRING)
	public String getCategoryName() {
		return mCategoryName;
	}

	public void setCategoryName(String categoryName) {
		this.mCategoryName = categoryName;
	}
}
