package com.logpie.shopping.tool.model;

import com.logpie.framework.db.annotation.DatabaseForeignKey;
import com.logpie.framework.db.annotation.DatabaseKey;
import com.logpie.framework.db.annotation.DatabaseKey.ColumnType;
import com.logpie.framework.db.annotation.DatabaseTable;
import com.logpie.shopping.tool.repository.CategoryRepository;
import com.logpie.shopping.tool.repository.SubCategoryRepository;

@DatabaseTable(name = SubCategoryRepository.DB_TABLE_NAME_SUBCATEGORY)
public class SubCategory extends LogpieModel {
	private String mSubCategoryId;
	private String mSubCategoryName;
	private Category mCategory;

	/**
	 * Constructor for creating a sub-category
	 * 
	 * @param subCategoryName
	 */
	public SubCategory(final String subCategoryName, final Category category) {
		this.mSubCategoryName = subCategoryName;
		this.mCategory = category;
	}

	/**
	 * 
	 * @param subCategoryId
	 * @param subCategoryName
	 */
	public SubCategory(final String subCategoryId,
			final String subCategoryName, final Category category) {
		this.mSubCategoryId = subCategoryId;
		this.mSubCategoryName = subCategoryName;
		this.mCategory = category;
	}

	@DatabaseKey(name = SubCategoryRepository.DB_KEY_SUBCATEGORY_ID, type = ColumnType.LONG, autoGenerated = true, isPrimaryKey = true)
	public String getSubCategoryId() {
		return mSubCategoryId;
	}

	@DatabaseKey(name = SubCategoryRepository.DB_KEY_SUBCATEGORY_NAME, type = ColumnType.STRING)
	public String getSubCategoryName() {
		return mSubCategoryName;
	}

	@DatabaseForeignKey(name = SubCategoryRepository.DB_KEY_CATEGORY_ID, type = ColumnType.LONG, referencedKey = CategoryRepository.DB_KEY_CATEGORY_ID, referencedTableModel = Category.class)
	public String getCategoryId() {
		return mCategory.getCategoryId();
	}

	public Category getCategory() {
		return mCategory;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.mSubCategoryName = subCategoryName;
	}

	public void setCategory(Category category) {
		this.mCategory = category;
	}

}
