package com.logpie.framework.db.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface AutoGenerate {
	/**
	 * declare two auto generate types in the database
	 * 
	 * @author xujiahang
	 *
	 */
	public enum AutoGenerateType {
		NumberAutoIncrement, CurrentTime
	}

	/**
	 * indicates that a key is auto-generated by database
	 * 
	 */
	public AutoGenerateType strategy();
}
