// Copyright 2017 logpie.com. All rights reserved.
package com.logpie.framework.db.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * specify the mapped database column for a method
 * 
 * @author xujiahang
 *
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface DatabaseKey {

	/**
	 *
	 * @return database key name
	 */
	public String name();

	/**
	 * declare five common types in the database
	 * 
	 * @author xujiahang
	 *
	 */
	public enum ColumnType {
		STRING, BOOLEAN, LONG, DOUBLE, TIMESTAMP
	}

	public ColumnType type();

	/**
	 * indicates that a key is auto-generated by database
	 * 
	 */
	public boolean autoGenerated() default false;

	public boolean isPrimaryKey() default false;

	public boolean unique() default false;
}
